# Data Cleaning

## Importing Packages

In [1]:
# importing necessary files
import pandas as pd

## Reading in Data

In [17]:
# reading in the historic dataframe
historic_df = pd.read_csv('../data/NABR_historic.csv') 
historic_df.head()

,long,lat,year,TimePeriod,RCP,scenario,treecanopy,Ann_Herb,Bare,Herb,...,PPT_Annual,T_Winter,T_Summer,T_Annual,Tmax_Summer,Tmin_Winter,VWC_Winter_whole,VWC_Spring_whole,VWC_Summer_whole,VWC_Fall_whole
0,-110.0472,37.60413,1980,Hist,historical,sc1,0,0,84,5,...,13.79,0.964835,23.15924,23.159240,37.05,NaN,NaN,NaN,NaN,NaN
1,-110.0472,37.60413,1980,Hist,historical,sc1,0,0,84,5,...,2.69,0.964835,23.15924,0.964835,37.05,NaN,NaN,NaN,NaN,NaN
2,-110.0472,37.60413,1980,Hist,historical,sc1,0,0,84,5,...,13.79,0.964835,23.15924,0.964835,37.05,NaN,NaN,NaN,NaN,NaN
3,-110.0472,37.60413,1980,Hist,historical,sc1,0,0,84,5,...,2.69,0.964835,23.15924,23.159240,37.05,NaN,NaN,NaN,NaN,NaN
4,-110.0472,37.60413,1980,Hist,historical,sc1,0,0,84,5,...,NaN,NaN,NaN,NaN,NaN,-12.45,0.113447,0.096831,0.041876,0.052298

In [19]:
# reading in the recent dataframe
recent_df = pd.read_csv('../data/nearterm_data_2020-2024.csv') 
recent_df.head()

,long,lat,year,TimePeriod,RCP,scenario,treecanopy,Ann_Herb,Bare,Herb,...,PPT_Annual,T_Winter,T_Summer,T_Annual,Tmax_Summer,Tmin_Winter,VWC_Winter_whole,VWC_Spring_whole,VWC_Summer_whole,VWC_Fall_whole
0,-110.0472,37.60413,2021,NT,4.5,sc22,0,0,84,5,...,6.37,1.630333,24.50402,24.50402,36.89,NaN,NaN,NaN,NaN,NaN
1,-110.0472,37.60413,2021,NT,4.5,sc22,0,0,84,5,...,NaN,NaN,NaN,NaN,NaN,-12.77,0.114652,0.078764,0.043514,0.051281
2,-110.0472,37.60413,2021,NT,4.5,sc23,0,0,84,5,...,3.09,1.389056,24.11043,24.11043,37.95,NaN,NaN,NaN,NaN,NaN
3,-110.0472,37.60413,2021,NT,4.5,sc23,0,0,84,5,...,NaN,NaN,NaN,NaN,NaN,-18.96,0.130221,0.096412,0.041232,0.092241
4,-110.0472,37.60413,2021,NT,4.5,sc24,0,0,84,5,...,6.87,-0.334389,25.54266,10.31321,37.74,NaN,NaN,NaN,NaN,NaN

## Initial EDA

### Data Shape

In [18]:
historic_df.shape

(13821, 29)

In [20]:
recent_df.shape

(55802, 29)

### Summary Statistics for Numerical Columns

In [21]:
historic_df.describe()

,long,lat,year,treecanopy,Ann_Herb,Bare,Herb,Litter,Shrub,DrySoilDays_Summer_whole,...,PPT_Annual,T_Winter,T_Summer,T_Annual,Tmax_Summer,Tmin_Winter,VWC_Winter_whole,VWC_Spring_whole,VWC_Summer_whole,VWC_Fall_whole
count,13821.000000,13821.000000,13821.000000,13821.000000,13821.000000,13821.000000,13821.000000,13821.000000,13821.000000,4476.000000,...,7930.000000,9453.000000,9453.000000,7930.000000,9453.000000,4476.000000,4476.000000,4476.000000,4476.000000,4476.000000
mean,-110.005518,37.608507,1998.889299,10.062586,0.228131,56.148976,9.553144,11.769626,15.482454,7.447274,...,7.335531,-0.141305,22.409513,10.722353,35.880022,-15.534115,0.119312,0.109115,0.068170,0.093811
std,0.022635,0.016206,11.283303,8.855615,1.069702,18.418774,3.887177,6.112302,8.594975,20.763970,...,3.619670,1.400045,1.024607,8.150340,1.346755,3.135112,0.037770,0.039504,0.018894,0.028577
min,-110.047200,37.570340,1980.000000,0.000000,0.000000,11.000000,1.000000,1.000000,0.000000,0.000000,...,1.760000,-3.434615,19.554890,-3.434615,32.150000,-26.250000,0.032807,0.034724,0.030281,0.031248
25%,-110.027300,37.598060,1989.000000,0.000000,0.000000,43.000000,8.000000,7.000000,10.000000,0.000000,...,4.870000,-1.228889,21.714130,2.312500,34.950000,-17.250000,0.091431,0.079048,0.052521,0.073958
50%,-110.005000,37.609150,1999.000000,9.000000,0.000000,54.000000,10.000000,10.000000,15.000000,0.000000,...,6.720000,-0.208333,22.327170,10.509780,35.850000,-14.950000,0.119300,0.101166,0.066038,0.092939
75%,-109.987800,37.622350,2009.000000,18.000000,0.000000,67.000000,11.000000,16.000000,20.000000,0.000000,...,9.690000,0.906593,23.132610,13.428020,37.050000,-13.850000,0.144474,0.138545,0.083102,0.111148
max,-109.965900,37.634760,2018.000000,29.000000,6.000000,94.000000,20.000000,26.000000,46.000000,89.000000,...,20.630000,3.393333,24.550000,24.550000,38.550000,-9.350000,0.232833,0.214546,0.119182,0.205399

Historical data ranges from 1980-2018.

In [22]:
recent_df.describe()

,long,lat,year,RCP,treecanopy,Ann_Herb,Bare,Herb,Litter,Shrub,...,PPT_Annual,T_Winter,T_Summer,T_Annual,Tmax_Summer,Tmin_Winter,VWC_Winter_whole,VWC_Spring_whole,VWC_Summer_whole,VWC_Fall_whole
count,55802.000000,55802.000000,55802.000000,55802.000000,55802.000000,55802.000000,55802.000000,55802.000000,55802.000000,55802.000000,...,32000.000000,37882.000000,37882.000000,32000.000000,37882.000000,18273.000000,18273.000000,18273.000000,18273.000000,18273.000000
mean,-110.006322,37.608169,2022.499211,6.501290,9.672682,0.226067,56.630497,9.506523,11.736192,15.348428,...,7.876302,1.061328,23.896685,11.987947,37.409251,-13.854524,0.130339,0.113198,0.069430,0.095702
std,0.022496,0.016194,1.117402,2.000018,8.785014,1.063672,18.480834,3.891147,6.101769,8.562249,...,4.170495,1.649202,1.160074,8.181101,1.886281,4.273170,0.039756,0.041728,0.019916,0.031099
min,-110.047200,37.570340,2021.000000,4.500000,0.000000,0.000000,11.000000,1.000000,1.000000,0.000000,...,0.430000,-5.392722,19.264730,-5.392722,31.370000,-30.270000,0.036778,0.032329,0.029968,0.031148
25%,-110.027300,37.598060,2022.000000,4.500000,0.000000,0.000000,45.000000,8.000000,8.000000,10.000000,...,4.790000,0.110056,23.150540,4.064556,36.280000,-16.470000,0.102253,0.079512,0.052745,0.073698
50%,-110.005700,37.608620,2022.000000,8.500000,9.000000,0.000000,56.000000,10.000000,10.000000,14.000000,...,7.300000,1.143556,23.927660,11.702030,37.400000,-12.900000,0.129224,0.105576,0.068260,0.092410
75%,-109.990900,37.621560,2023.000000,8.500000,18.000000,0.000000,67.000000,11.000000,16.000000,20.000000,...,10.360000,2.135722,24.576680,14.686260,38.290000,-10.950000,0.155793,0.144423,0.084791,0.112807
max,-109.965900,37.634760,2024.000000,8.500000,29.000000,6.000000,94.000000,20.000000,26.000000,46.000000,...,33.730000,5.474725,27.745330,27.745330,47.170000,-6.510000,0.241642,0.219919,0.145245,0.230940

Recent data ranges from 2021-2024.

### Column Datatypes

In [24]:
historic_df.dtypes

long                                      float64
lat                                       float64
year                                        int64
TimePeriod                                 object
RCP                                        object
scenario                                   object
treecanopy                                  int64
Ann_Herb                                    int64
Bare                                        int64
Herb                                        int64
Litter                                      int64
Shrub                                       int64
DrySoilDays_Summer_whole                  float64
Evap_Summer                               float64
ExtremeShortTermDryStress_Summer_whole    float64
FrostDays_Winter                          float64
NonDrySWA_Summer_whole                    float64
PPT_Winter                                float64
PPT_Summer                                float64
PPT_Annual                                float64
T_Winter                                  float64
T_Summer                                  float64
T_Annual                                  float64
Tmax_Summer                               float64
Tmin_Winter                               float64
VWC_Winter_whole                          float64
VWC_Spring_whole                          float64
VWC_Summer_whole                          float64
VWC_Fall_whole                            float64
dtype: object

In [25]:
recent_df.dtypes

long                                      float64
lat                                       float64
year                                        int64
TimePeriod                                 object
RCP                                       float64
scenario                                   object
treecanopy                                  int64
Ann_Herb                                    int64
Bare                                        int64
Herb                                        int64
Litter                                      int64
Shrub                                       int64
DrySoilDays_Summer_whole                  float64
Evap_Summer                               float64
ExtremeShortTermDryStress_Summer_whole    float64
FrostDays_Winter                          float64
NonDrySWA_Summer_whole                    float64
PPT_Winter                                float64
PPT_Summer                                float64
PPT_Annual                                float64
T_Winter                                  float64
T_Summer                                  float64
T_Annual                                  float64
Tmax_Summer                               float64
Tmin_Winter                               float64
VWC_Winter_whole                          float64
VWC_Spring_whole                          float64
VWC_Summer_whole                          float64
VWC_Fall_whole                            float64
dtype: object